# permissions for end users to edit sams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sam-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sam-operator
    app.kubernetes.io/part-of: sam-operator
    app.kubernetes.io/managed-by: kustomize
  name: sam-editor-role
rules:
- apiGroups:
  - sam.io
  resources:
  - sams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sam.io
  resources:
  - sams/status
  verbs:
  - get
